# Generated by Django 4.2.8 on 2025-06-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konac', '0001_initial'),
    ]

    operations = [
    ]
