# Generated by Django 4.2.8 on 2025-06-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsubscriber',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
